[package]
name = "asteroid_dodge"
version = "0.1.0"
edition = "2024"

[dependencies]
avian2d = "0.4.1"
bevy = {version = "0.17.2", features = ["jpeg", "png"]}
bevy_asset = "0.17.2"
bevy_mesh = "0.17.2"
rand = "0.9.2"
wgpu-types = "24.0"

[dev-dependencies]
image = "0.24"
